Repository Pavan-Kamthane/Java-Programs, pull requests merged in 2022-10, with the labels that each got.

#2 Bubble Sort
  Sort
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#5 A program for setting the kth bit
  SettingKthBit.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#6 fibonacci program added in java
  fibonacci.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#8 Added a Java Program to Find ASCII value of a character
  AsciiValue.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#9 added two sum code in java
  twoSum.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#11 Added Sorting Algorithm in Java
  Sorting/BubbleSort.java
  Sorting/InsertionSort.java
  Sorting/SelectionSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#14 OddEven number in java
  OddEven.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#15 Smallest subset with greatest sum code is added
  Stack.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#16 hacktoberfest2022
  Sorting/QuickSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#17 Added code to count occurrence of a character
  ShaluMishra13
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#18 Create LCM.java
  LCM.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#19 Second largest element in array
  secondlargest.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#20 Create emirp.java
  emirp.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#21 Create duplicateWordsInString.java
  Strings/duplicateWordsInString.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#22 HactoberFest2022
  FibonacciExample1.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#23 Hacktoberfest
  MergeArray.java
Labels: hacktoberfest-accepted, hacktoberfest-2022

#24 Integer to Roman in Java
  Roman.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#25 Dublicate in array
  dublicateInArray.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#26 Hacktoberfest-2022
  java program.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#27 leap year
  leap_year_again.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#32 Hacktoberfest2022
  javaleap.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#31 please accept this java program palindrome.java
  palindrome.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#30 Longest Substring problem added #4
  Strings/LongestNonRepeatingSubstring.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#29 hacktoberfest2022
  Sorting/Radix_sorting.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#28 concatenation of string
  Strings/concatenation.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#33 Add OddEven Sort
  Sorting/OddEvenSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#35 Find Armstrong number between two integers program in java
  ArmstrongBetweenTwoIntegers.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#36 Hactoberfest2022--> fibonacci_series.java
  fibonacci_series.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#34 hacktoberfest2022
  Absolute.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#39 hacktoberfest2022
  java program
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#41 Created mergesort.java
  Searching/mergesort.java
Labels: hacktoberfest-accepted, hacktoberfest-2022

#44 hacktoberfest2022
  diameter_binarytree.java
  diameter_of_binarytree.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#45 Create Krishnangshu Paul
  Krishnangshu Paul
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#43 added bucketSort.cpp
  Sorting/bucketSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#40 hacktoberfest2022
  main.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#42 added Container With Most Water.java
  Container With Most Water.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#46 Java AWT Framework Swap Two Numbers Program
  swap.form
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#47 hacktoberfest2022
  recursion21.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#48 multithreading.java
  multithreading.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#49 Calculator java
  calc.java
Labels: hacktoberfest, hacktoberfest-2022

#50 hacktoberfest2022
  pyramidstar.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#64 Added Java Swing Project
  .netbeans_automatic_build
  .netbeans_update_resources
  Category1.form
  Category1.java
  Customer.form
  Customer.java
  Demo.java
  HomeForm.form
  HomeForm.java
  Login.form
  Login.java
  Order.form
  Order.java
  PreparedStatement.java
  Product.java
  README.TXT
  Splash.form
  Splash.java
  Student.class
  User.form
  User.java
  Web-based-inventory-management.png
  add.java
  b.class
  b.java
  backSplash.jpg
  backbutton-removebg-preview.png
  backbutton.jpg
  build.xml
  built-jar.properties
  inventoryManagementSystem.jar
  manifest.mf
  order.png
  product.png
  stock count.png
  user.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#63 Binary Tree
  BinaryTree.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#62 Added a simple java program for inheritance
  Inheritance/Animal.java
  Inheritance/Dog.java
  Inheritance/Main.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#60 Create MergeSort.java
  Sorting/MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#59 Added cyclic sort in java
  Sorting/Cyclicsort.java
Labels: hacktoberfest-accepted, hacktoberfest-2022

#58 Create warshall.java
  warshall.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#56 added palindrome program
  palindrome/palindrome-2.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#57 Added a Java JUMP GAME.
  Jump Game
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#54 Java Fair Candy Swap Program.
  Fair Candy Swap
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#53 Java Program for 4SUM Problem.
  4SUM
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#61 permutation.java
  permutation.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#68 Created Invest.java
  Varad Chandrawar/invest.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#69 Craeted sum.java
  Varun Kotgire/sum.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#67 Added a simple java program for array sort
  arraySort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#66 Sorting an array of Triplet
  Sort an Array of Triplet using Java Comparable and Comparator/Gk.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#71 hacktoberfest2022
  kaveri5764
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#74 method
  athul/metho.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#73 Added a simple java program to find the element is minimum or maximum
  MinMax.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#75 simple book management using linkedlist in java
  library_linkedlist/Lib.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#76 Added Kadane's Algorithm
  KadaneAlgo.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#80 SelectionSort.java
  Sorting/SelectionSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#79 Added BFS Algo
  BFS.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#78 QuickSortAlgorathim.java
  Sorting/QuickSortAlgorathim.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#77 Create Interface in Java
  Interfaces in Java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#81 Create Average.java
  Average.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#85 hactoberfest2022
  a.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#83 Create reverse_words.java
  reverse_words.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#82 added calculator
  Calculator.java
  Conditionals.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#87 Create InsertionSort.java
  Sorting/InsertionSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#89 Create Client.java
  Simple Chat Project/Client.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#93 Fibonacci Series program using Java by Yash Mittal
  fibonacci.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#92 Longest_Palindromic_Substring.java
  Beginner-level- java programs/palindrome/Longest_Palindromic_Substring.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#91 added palindrome_string program
  Alok Singh/palindrome.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#90 Adding Files in Simple Chat Project
  Quiz Project/AnswerKey.txt
  Quiz Project/Client.java
  Quiz Project/ClientThread.java
  Quiz Project/General_Knowledge.txt
  Quiz Project/General_Knowledge_sol.txt
  Quiz Project/Host.java
  Quiz Project/Initiator.java
  Quiz Project/Main.java
  Quiz Project/Questions.txt
  Quiz Project/Science.txt
  Quiz Project/Science_sol.txt
  Quiz Project/Set_time.java
  Quiz Project/programming.txt
  Quiz Project/programming_sol.txt
  Quiz Project/question_setter.java
  Quiz Project/reader.java
  Quiz Project/subject_selector.java
  Quiz Project/timer.java
  Simple Chat Project/Server.java
  Simple Chat Project/mclient.java
  Simple Chat Project/mserver.java
Labels: hacktoberfest-accepted, hacktoberfest-2022

#94 Bubble sort algorithm in java added
  Sorting/BubbleSortAlgorithmEx.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#95 String Sorting in Java
  String_Sort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#96 Transpose of matrix using java by Yash Mittal
  transpose.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#97 deleted cpp
  intermediate_level java program/Sorting/bucketSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2022

#98 Create addition.java
  addition.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#99 Create RotateArray.java
  RotateArray.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#102 Snake Game with Different Playing Features and GUI
  Mental Health Check A Quiz Application/MHS.java
  Mental Health Check A Quiz Application/README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#101 hacktoberfest2022
  binary_search.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#103 Create printDiagonal.java
  printDiagonal.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#104 Add files via upload
  fibonacci.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#105 Created GayleShapleyAlgorithm.java
  GayleShapleyAlgorithm.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#107 Add files via upload
  palindrome.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#106 Create RTO number plate generation
  RTO_number_plate_generation.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#100 hacktoberfest2022
  sort_array.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#108 Tic Tac Toe Game
  tictactoe.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#114 created Linear search by java
  linear search by java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#113 Radix Sort using Java by Jatin
  radix.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#112 hacktoberfest2022
  Sorting/BucketSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#111 Hacktoberfest2022
  JavaS.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#110 Hacktoberfest2022
  Sortjava.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#109 Create Palindrome_using_recursion.java
  Palindrome_using_recursion.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#115 Added a program of bubble sort
  Bubble Sort.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#116 hacktoberfest2022
  java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#118 Sieve Of Eratosthenes
  SieveOfEratosthenes.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#117 rock_paper_scissors.java
  rock_paper_scissors.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#119 Hacktoberfest2022
  JProgram.java
Labels: hacktoberfest-accepted, hacktoberfest-2022

#121 shaziaah19 - Sudoku Solver Leetcode 37
  Sudoku Solver Leetcode 37/Q37.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#120 Binary Search tree using java
  Binary Search Tree/BinarySearchTree$Node.class
  Binary Search Tree/BinarySearchTree.class
  Binary Search Tree/BinarySearchTree.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#125 Java code
  Beginner-level- java programs/fibonacci.java
  Sorting/MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#123 added pascal triangle code in java.
  PascalTriangle.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#126 add interface for student/professor
  mahrukh/Person.java
  mahrukh/Professor.java
  mahrukh/Student.java
  mahrukh/main.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#128 krushkal's Algorithm in Java
  Krushkal.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#136 Create MovieTicketBooking.java
  ticket-bookingsystem/MovieTicketBooking.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#134 Add files via upload
  SumTriangleFromArray.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#133 Hactoberfestin2022
  Conversion binary to octal.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#132 Hacktoberfest2K22
  Hello world.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#131 Added PascalTriangle.java
  Beginner-level- java programs/PascalTriangle.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#141 Create&write_File.java
  create_File.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#139 hacktober pr
  Ritik Singh/.idea/misc.xml
  Ritik Singh/.idea/modules.xml
  Ritik Singh/.idea/vcs.xml
  Ritik Singh/.idea/workspace.xml
  Ritik Singh/Ritik Singh.iml
  Ritik Singh/out/production/Ritik Singh/Main.class
  Ritik Singh/src/Main.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#140 Merge Sort
  Merge Sort.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#138 Validate IP Address
  Validate_IP_Addess.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#137 Java programs in data structure and algorithum.
  circular_linkedList.java
  java_swing.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#150 Palindrome_LinkedList.java
  palindromeusingsinglylinkedlist.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#149 Create jumpsearch21.java
  jumpsearch21.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#148 Special Two Digit Number
  special_twodigit_number.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#146 Implementation of Insertion Sort in Java
  InsertionSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#145 Reversing_LinkedList.java
  Reversing_Linkedlist.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#144 Checksum
  Checksum_Program/Checksum.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#152 Create MapOfIndia.java
  MapOfIndia.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#153 Create Good 👍
  Good 👍
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#154 HACKTOBERFEST 2022
  N-Queen(SFS)107.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#155 HACKTOBERFEST 2022
  N-Queen(SSF)106.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#156 HACKTOBERFEST 2022
  N-Queen(FSS)105.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#164 Create Keith_Number.java
  Keith_Number.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#163 Hacktoberfest2022
  Binarytree.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#162 Hacktoberfest2022
  Factor.Java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#161 Largest_smallest_word_in_a_sentence.java
  largest_smallest_word_in_a_sentence.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#160 new simple java program that I learn
  jobSalary.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#159 This program Changes Decimal Number to binary.
  binaryNum.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#158 Create Currency_Converter.java
  Currency_Converter.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#157 hacktoberfest2022
  Selection-sorting.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#167 Small Projects in java
  small_project.java/Temperatutre_converter.java
  small_project.java/currency_converter.java
  small_project.java/ip_validator.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#166 Number Guessing Game in Java
  numGuess.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#165 Malsha
  Beginner-level- java programs/Id_Sorting.java
  Beginner-level- java programs/Sorting_pots.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#188 User can input the number of rows to be printed
  Pattern.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#187 Issue #129 - Added design-pattern repository and Singleton Design Pat…
  design-patterns-by Nilesh-Ghone/creational/singleton/EagerInitializedSingleton.java
  design-patterns-by Nilesh-Ghone/creational/singleton/LazyInitializedSingleton.java
  design-patterns-by Nilesh-Ghone/creational/singleton/StaticBlockSingleton.java
  design-patterns-by Nilesh-Ghone/creational/singleton/ThreadSafeSingleton.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#185 Upper Triangle Matrix in Java
  UpperTriangularMatrix.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#184 Added Single Element question of LeetCode.
  singleElement.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#183 Added Peak Of Mountain Array question of LeetCode.
  peakMountain.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#182 Added Binary Search in Matrix.
  matrixBinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#181 Added Binary Search
  Binary Search/binarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#180 added java program
  Ayush Mokal/prime.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#178 binary search using character array
  binary search using charcter array.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#168 Add rsa encryption file
  Binarytree.java
  RSA_ENCRYPTION.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022

#169 added some begineer friendly java programs
  .classpath
  .project
  Begineer Friendly Java Programs/PerfectNumber.java
  BinaryTree.java
  NumberToWords.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022
